EIP1-NONE: Add test pipeline check for migration files

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -12,6 +12,25 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
+
+      # First check DB migrations are unique and have been added to the changelog master file before any slow actions
+      - name: Check DB migration numbers are unique
+        run: |
+          EXIT_CODE=0
+          NON_UNIQUE=$(ls src/main/resources/db/changelog/create/ | awk -F_ '{print $1}' | uniq -cd)
+          if [[ ${#NON_UNIQUE} != 25 ]]; then # there were already a few duplicates before this check was added which is why the check is not for an empty list
+            echo -e "::error::A migration number was found multiple times, see duplicates in 'count duplicate_prefix' pairs: \n$NON_UNIQUE"
+            EXIT_CODE=1
+          fi
+          for MIGRATION in src/main/resources/db/changelog/create/*; do
+            if [[ $(grep -c `basename "$MIGRATION"` src/main/resources/db/changelog/db.changelog-master.yaml) == 0 ]]; then
+              echo "Migration: $MIGRATION has not been added to src/main/resources/db/changelog/db.changelog-master.yaml"
+              EXIT_CODE=1
+            fi
+          done
+          exit $EXIT_CODE
+
+
       # Installing JDK needs to come after checking out the repo because the action (setup-java) looks for the gradle wrapper files
       - name: Install JDK 17
         uses: actions/setup-java@v3
